=== segmeton/WorldEndTale-Original-/Assets/DB/Accessory.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Accessory" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Accessory">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="CQKOAVrLZ02Oqb+Hz3iLLQ==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAAJAo4BWstnTY6pv4fPeIstAAAAAB70k4ROfuRAAAAAAAAAAABBAGMA
YwBlAHMAcwBvAHIAeQAAAAAAAACm19x0pUL9TY1s/AHFpLekBwAAAAkCjgFay2dN
jqm/h894iy1JAEQAAAAAAAAAyueizETsHkeJlUf2t7b5ZQcAAAAJAo4BWstnTY6p
v4fPeIstTgBhAG0AZQAAAAAAAABpJvLNquFDRIHMXuZR0E5qBwAAAAkCjgFay2dN
jqm/h894iy1CAHUAeQAgAFAAcgBpAGMAZQAAAAAAAAAdr5PH7+J5T4qXTAe3pQeH
BwAAAAkCjgFay2dNjqm/h894iy1TAGUAbABsACAAUAByAGkAYwBlAAAAAAAAACBJ
gDiNwgNBlnzNTI2Ab7oHAAAACQKOAVrLZ02Oqb+Hz3iLLVMAVABSAAAAAAAAALrd
9dgSIBJGgqLOgm7HpMgHAAAACQKOAVrLZ02Oqb+Hz3iLLU0AQQBHAAAAAAAAAIKd
/nb2WD5CosGTMQ9XQTkHAAAACQKOAVrLZ02Oqb+Hz3iLLUUATgBEAAAAAAAAAAPJ
etFh7JBKt15FmWN0QA8HAAAACQKOAVrLZ02Oqb+Hz3iLLUEARwBJAAAAAAAAAH6d
BU8GdC9CluvYntavUlEHAAAACQKOAVrLZ02Oqb+Hz3iLLUEAQwBDAAAAAAAAAPGS
uRZ+TElEiIzaKBhK2qgHAAAACQKOAVrLZ02Oqb+Hz3iLLUQAZQBzAGMAcgBpAHAA
dABpAG8AbgAAAAAAAADvjMfPenX6QqA2qIk2z7IuBwAAAAkCjgFay2dNjqm/h894
iy1VAHMAZQBkACAAYgB5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABQAAAAAA
AAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="0"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="yueizETsHkeJlUf2t7b5ZQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1884"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="0"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Buy_x0020_Price" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="aSbyzarhQ0SBzF7mUdBOag==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Sell_x0020_Price" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="Ha+Tx+/ieU+Kl0wHt6UHhw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="STR" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="IEmAOI3CA0GWfM1MjYBvug==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="MAG" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="ut312BIgEkaCos6CbsekyA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="END" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="gp3+dvZYPkKiwZMxD1dBOQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="AGI" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="A8l60WHskEq3XkWZY3RADw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ACC" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="fp0FTwZ0L0KW69ie1q9SUQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Description" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="8ZK5Fn5MSUSIjNooGEraqA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="4332"/>
<od:fieldProperty name="ColumnOrder" type="3" value="10"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="0"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== segmeton/WorldEndTale-Original-/Assets/DB/Accessory.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Accessory.xsd" generated="2014-11-30T21:48:46">
<Accessory>
<ID>AC01</ID>
<Name>Enchanted Ring</Name>
<Buy_x0020_Price>500</Buy_x0020_Price>
<Sell_x0020_Price>250</Sell_x0020_Price>
<STR>5</STR>
<MAG>5</MAG>
<END>0</END>
<AGI>0</AGI>
<ACC>0</ACC>
<Description>A ring enchanted by a Mage</Description>
</Accessory>
<Accessory>
<ID>AC02</ID>
<Name>Targeting Scope</Name>
<Buy_x0020_Price>500</Buy_x0020_Price>
<Sell_x0020_Price>250</Sell_x0020_Price>
<STR>0</STR>
<MAG>0</MAG>
<END>0</END>
<AGI>0</AGI>
<ACC>5</ACC>
<Description>Scope to see in more detail</Description>
</Accessory>
<Accessory>
<ID>AC03</ID>
<Name>Iron Bracelet</Name>
<Buy_x0020_Price>500</Buy_x0020_Price>
<Sell_x0020_Price>250</Sell_x0020_Price>
<STR>0</STR>
<MAG>0</MAG>
<END>10</END>
<AGI>0</AGI>
<ACC>0</ACC>
<Description>A bracelet made of iron</Description>
</Accessory>
<Accessory>
<ID>AC04</ID>
<Name>Crystal Necklace</Name>
<Buy_x0020_Price>500</Buy_x0020_Price>
<Sell_x0020_Price>250</Sell_x0020_Price>
<STR>0</STR>
<MAG>10</MAG>
<END>0</END>
<AGI>0</AGI>
<ACC>0</ACC>
<Description>Necklace with little crystal attached</Description>
</Accessory>
<Accessory>
<ID>AC05</ID>
<Name>Enchancer Gem</Name>
<Buy_x0020_Price>1500</Buy_x0020_Price>
<Sell_x0020_Price>750</Sell_x0020_Price>
<STR>10</STR>
<MAG>10</MAG>
<END>0</END>
<AGI>0</AGI>
<ACC>0</ACC>
<Description>A gem enchanted by a Mage</Description>
</Accessory>
<Accessory>
<ID>AC06</ID>
<Name>Surefire Glasses</Name>
<Buy_x0020_Price>1500</Buy_x0020_Price>
<Sell_x0020_Price>750</Sell_x0020_Price>
<STR>0</STR>
<MAG>0</MAG>
<END>0</END>
<AGI>0</AGI>
<ACC>10</ACC>
<Description>Glasses to see in more detail</Description>
</Accessory>
<Accessory>
<ID>AC07</ID>
<Name>Steel Shield</Name>
<Buy_x0020_Price>1500</Buy_x0020_Price>
<Sell_x0020_Price>750</Sell_x0020_Price>
<STR>0</STR>
<MAG>0</MAG>
<END>20</END>
<AGI>0</AGI>
<ACC>0</ACC>
<Description>A very hard shield made from Steel</Description>
</Accessory>
<Accessory>
<ID>AC08</ID>
<Name>Magic Amulet</Name>
<Buy_x0020_Price>1500</Buy_x0020_Price>
<Sell_x0020_Price>750</Sell_x0020_Price>
<STR>0</STR>
<MAG>20</MAG>
<END>0</END>
<AGI>0</AGI>
<ACC>0</ACC>
<Description>Amulet with little crystal attached</Description>
</Accessory>
<Accessory>
<ID>AC09</ID>
<Name>Devil&apos;s Rosary</Name>
<Buy_x0020_Price>0</Buy_x0020_Price>
<Sell_x0020_Price>2500</Sell_x0020_Price>
<STR>20</STR>
<MAG>20</MAG>
<END>20</END>
<AGI>20</AGI>
<ACC>20</ACC>
<Description>A memento of a best friend</Description>
</Accessory>
<Accessory>
<ID>AC10</ID>
<Name>Crystal Ball</Name>
<Buy_x0020_Price>0</Buy_x0020_Price>
<Sell_x0020_Price>2000</Sell_x0020_Price>
<STR>0</STR>
<MAG>30</MAG>
<END>0</END>
<AGI>30</AGI>
<ACC>30</ACC>
<Description>A pure lump of crystal that has divination power</Description>
</Accessory>
<Accessory>
<ID>AC11</ID>
<Name>Impenetrable Shield</Name>
<Buy_x0020_Price>0</Buy_x0020_Price>
<Sell_x0020_Price>2000</Sell_x0020_Price>
<STR>30</STR>
<MAG>0</MAG>
<END>30</END>
<AGI>10</AGI>
<ACC>20</ACC>
<Description>A shield said to be the strongest in the world</Description>
</Accessory>
</dataroot>
