=== segmeton/WorldEndTale-Original-/Assets/DB/Armor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Armor" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Armor">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="PCy+1ALEJkWvOQS+ZJksHQ==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAA8LL7UAsQmRa85BL5kmSwdAAAAALv8OWBOfuRAAAAAAAAAAABBAHIA
bQBvAHIAAAAAAAAAN7S2L290fkKqjEvQZOVVkQcAAAA8LL7UAsQmRa85BL5kmSwd
SQBEAAAAAAAAAC4tfSAhqI5Ihmu7oM7AunwHAAAAPCy+1ALEJkWvOQS+ZJksHU4A
YQBtAGUAAAAAAAAAkna2CWRvq0yCNu916LsMVAcAAAA8LL7UAsQmRa85BL5kmSwd
QgB1AHkAIABQAHIAaQBjAGUAAAAAAAAAdA2z2pHVt0W2AYFN6UmQTAcAAAA8LL7U
AsQmRa85BL5kmSwdUwBlAGwAbAAgAFAAcgBpAGMAZQAAAAAAAACKQdDpvv+KR6mo
8QqihFycBwAAADwsvtQCxCZFrzkEvmSZLB1TAFQAUgAAAAAAAADLvLlKD0EBSa7y
AN4oZHkbBwAAADwsvtQCxCZFrzkEvmSZLB1NAEEARwAAAAAAAABRMNt3d0clSY2S
kjXrthXqBwAAADwsvtQCxCZFrzkEvmSZLB1FAE4ARAAAAAAAAABHONZyhTqaQo8K
DSlDPwavBwAAADwsvtQCxCZFrzkEvmSZLB1BAEcASQAAAAAAAAADOMpOj2iBQoA7
p7/Z3joUBwAAADwsvtQCxCZFrzkEvmSZLB1EAGUAcwBjAHIAaQBwAHQAaQBvAG4A
AAAAAAAAE2NunYnf9k+DHaFTTnc+EwcAAAA8LL7UAsQmRa85BL5kmSwdVQBzAGUA
ZAAgAGIAeQAAAAAAAABVRblF0jUkSKhnyMoCHNndBwAAADwsvtQCxCZFrzkEvmSZ
LB1BAEMAQwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUAAAAAAAAAAAAAAAAA
AAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="672"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="0"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="Li19ICGojkiGa7ugzsC6fA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1608"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="0"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Buy_x0020_Price" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="kna2CWRvq0yCNu916LsMVA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1188"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Sell_x0020_Price" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="dA2z2pHVt0W2AYFN6UmQTA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1164"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="STR" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="ikHQ6b7/ikepqPEKooRcnA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1296"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="MAG" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="y7y5Sg9BAUmu8gDeKGR5Gw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="END" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="UTDbd3dHJUmNkpI167YV6g==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="AGI" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="RzjWcoU6mkKPCg0pQz8Grw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ACC" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="VUW5RdI1JEioZ8jKAhzZ3Q==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Description" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="3948"/>
<od:fieldProperty name="ColumnOrder" type="3" value="10"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="0"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextFormat" type="2" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AppendOnly" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="AzjKTo9ogUKAO6e/2d46FA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== segmeton/WorldEndTale-Original-/Assets/DB/Armor.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Armor.xsd" generated="2014-11-30T21:50:42">
<Armor>
<ID>AR01</ID>
<Name>Robe</Name>
<Buy_x0020_Price>0</Buy_x0020_Price>
<Sell_x0020_Price>50</Sell_x0020_Price>
<STR>0</STR>
<MAG>0</MAG>
<END>5</END>
<AGI>0</AGI>
<ACC>0</ACC>
<Description>A robe used by travellers</Description>
</Armor>
<Armor>
<ID>AR02</ID>
<Name>Reinforced Robe</Name>
<Buy_x0020_Price>300</Buy_x0020_Price>
<Sell_x0020_Price>150</Sell_x0020_Price>
<STR>0</STR>
<MAG>0</MAG>
<END>15</END>
<AGI>0</AGI>
<ACC>0</ACC>
<Description>A robe made stronger using magic</Description>
</Armor>
<Armor>
<ID>AR03</ID>
<Name>Magician&apos;s Robe</Name>
<Buy_x0020_Price>1000</Buy_x0020_Price>
<Sell_x0020_Price>500</Sell_x0020_Price>
<STR>0</STR>
<MAG>10</MAG>
<END>30</END>
<AGI>0</AGI>
<ACC>0</ACC>
<Description>The robe that was worn by Royal Magicians</Description>
</Armor>
<Armor>
<ID>AR04</ID>
<Name>Sacred Garment</Name>
<Buy_x0020_Price>5000</Buy_x0020_Price>
<Sell_x0020_Price>2500</Sell_x0020_Price>
<STR>10</STR>
<MAG>25</MAG>
<END>50</END>
<AGI>10</AGI>
<ACC>5</ACC>
<Description>A Cloth blessed by the Goddess of Life</Description>
</Armor>
<Armor>
<ID>AR05</ID>
<Name>Leather Armor</Name>
<Buy_x0020_Price>0</Buy_x0020_Price>
<Sell_x0020_Price>50</Sell_x0020_Price>
<STR>0</STR>
<MAG>0</MAG>
<END>7</END>
<AGI>0</AGI>
<ACC>0</ACC>
<Description>An armor made of leather</Description>
</Armor>
<Armor>
<ID>AR06</ID>
<Name>Spike Armor</Name>
<Buy_x0020_Price>300</Buy_x0020_Price>
<Sell_x0020_Price>150</Sell_x0020_Price>
<STR>5</STR>
<MAG>0</MAG>
<END>15</END>
<AGI>0</AGI>
<ACC>0</ACC>
<Description>Iron armor with jutting spikes</Description>
</Armor>
<Armor>
<ID>AR07</ID>
<Name>Mithril Mail</Name>
<Buy_x0020_Price>1000</Buy_x0020_Price>
<Sell_x0020_Price>500</Sell_x0020_Price>
<STR>0</STR>
<MAG>0</MAG>
<END>30</END>
<AGI>0</AGI>
<ACC>0</ACC>
<Description>A very hard armor made from Mithril</Description>
</Armor>
<Armor>
<ID>AR08</ID>
<Name>King&apos;s Raiments</Name>
<Buy_x0020_Price>5000</Buy_x0020_Price>
<Sell_x0020_Price>2500</Sell_x0020_Price>
<STR>20</STR>
<MAG>10</MAG>
<END>60</END>
<AGI>5</AGI>
<ACC>10</ACC>
<Description>The armor used by kings</Description>
</Armor>
<Armor>
<ID>AR09</ID>
<Name>Paladin Armor</Name>
<Buy_x0020_Price>5000</Buy_x0020_Price>
<Sell_x0020_Price>2500</Sell_x0020_Price>
<STR>25</STR>
<MAG>0</MAG>
<END>70</END>
<AGI>0</AGI>
<ACC>5</ACC>
<Description>A sacred battle garb for Holy Knights</Description>
</Armor>
</dataroot>
