=== segmeton/WorldEndTale-Original-/Assets/DB/Enemy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Enemy" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Enemy">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="c07MYe6yJEyzMktu/7pYTw==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAABzTsxh7rIkTLMyS27/ulhPAAAAAIZ8gt+yfuRAAAAAAAAAAABFAG4A
ZQBtAHkAAAAAAAAAGqEibC/SPU+iZ7V96KfW9QcAAABzTsxh7rIkTLMyS27/ulhP
SQBEAAAAAAAAAAsipWclzsVGqSIMJYEPvAIHAAAAc07MYe6yJEyzMktu/7pYT04A
YQBtAGUAAAAAAAAAqXii6XWicUqDoiaZnVCnYQcAAABzTsxh7rIkTLMyS27/ulhP
SABQAAAAAAAAAEivKT9ZO8xGr05+QOUc1EIHAAAAc07MYe6yJEyzMktu/7pYT00A
UAAAAAAAAAAEuDD7KV5JTbrrhufC43Y1BwAAAHNOzGHusiRMszJLbv+6WE9TAFQA
UgAAAAAAAADGdevj8eoXQbKTbB46TgxABwAAAHNOzGHusiRMszJLbv+6WE9FAE4A
RAAAAAAAAAA4U0awRvE3Tb6rRuGR1VfCBwAAAHNOzGHusiRMszJLbv+6WE9NAEEA
RwAAAAAAAABPdhoRtcRcQ48EMEO0opnTBwAAAHNOzGHusiRMszJLbv+6WE9BAEcA
SQAAAAAAAACZMpPjYhIYRq9JqxhkjryUBwAAAHNOzGHusiRMszJLbv+6WE9BAEMA
QwAAAAAAAAB9+ICCOWlaQrUBt8GRquvnBwAAAHNOzGHusiRMszJLbv+6WE9MAGUA
dgBlAGwAAAAAAAAAFiCW9BxCj0+Br4lAzI54swcAAABzTsxh7rIkTLMyS27/ulhP
RQBYAFAAAAAAAAAAFbxVCjM0u0uYhOx/T7IYygcAAABzTsxh7rIkTLMyS27/ulhP
RwBvAGwAZAAAAAAAAACNmw67iaNKSbYPXUQzdyp1BwAAAHNOzGHusiRMszJLbv+6
WE9FAGwAZQBtAGUAbgB0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABQAAAAAA
AAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="OrderBy" type="12" value="[Enemy].[ID]"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="0"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="GqEibC/SPU+iZ7V96KfW9Q==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="CyKlZyXOxUapIgwlgQ+8Ag==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="0"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="HP" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="qXii6XWicUqDoiaZnVCnYQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="MP" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="SK8pP1k7zEavTn5A5RzUQg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="STR" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="BLgw+yleSU2664bnwuN2NQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="END" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="xnXr4/HqF0Gyk2weOk4MQA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="MAG" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="OFNGsEbxN02+q0bhkdVXwg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="AGI" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="T3YaEbXEXEOPBDBDtKKZ0w==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ACC" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="mTKT42ISGEavSasYZI68lA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Level" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="ffiAgjlpWkK1AbfBkarr5w==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1596"/>
<od:fieldProperty name="ColumnOrder" type="3" value="10"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="EXP" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="FiCW9BxCj0+Br4lAzI54sw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="11"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Gold" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="FbxVCjM0u0uYhOx/T7IYyg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="12"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Element" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="jZsOu4mjSkm2D11EM3cqdQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="13"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="0"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== segmeton/WorldEndTale-Original-/Assets/DB/Enemy.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Enemy.xsd" generated="2014-12-16T23:55:12">
<Enemy>
<ID>EN01</ID>
<Name>Slime</Name>
<HP>10</HP>
<MP>15</MP>
<STR>10</STR>
<END>5</END>
<MAG>10</MAG>
<AGI>8</AGI>
<ACC>5</ACC>
<Level>1</Level>
<EXP>500</EXP>
<Gold>12</Gold>
<Element>Water</Element>
</Enemy>
<Enemy>
<ID>EN02</ID>
<Name>Zombie</Name>
<HP>10</HP>
<MP>20</MP>
<STR>10</STR>
<END>5</END>
<MAG>15</MAG>
<AGI>10</AGI>
<ACC>10</ACC>
<Level>2</Level>
<EXP>500</EXP>
<Gold>15</Gold>
<Element>Dark</Element>
</Enemy>
<Enemy>
<ID>EN03</ID>
<Name>Ghost</Name>
<HP>10</HP>
<MP>30</MP>
<STR>10</STR>
<END>5</END>
<MAG>65</MAG>
<AGI>17</AGI>
<ACC>14</ACC>
<Level>3</Level>
<EXP>500</EXP>
<Gold>20</Gold>
<Element>Wind</Element>
</Enemy>
<Enemy>
<ID>EN04</ID>
<Name>Lightning Tiger</Name>
<HP>120</HP>
<MP>40</MP>
<STR>70</STR>
<END>30</END>
<MAG>35</MAG>
<AGI>40</AGI>
<ACC>20</ACC>
<Level>4</Level>
<EXP>29</EXP>
<Gold>40</Gold>
<Element>Electric</Element>
</Enemy>
<Enemy>
<ID>EN05</ID>
<Name>Mad Rider</Name>
<HP>150</HP>
<MP>50</MP>
<STR>90</STR>
<END>40</END>
<MAG>20</MAG>
<AGI>20</AGI>
<ACC>13</ACC>
<Level>5</Level>
<EXP>31</EXP>
<Gold>50</Gold>
<Element>Neutral</Element>
</Enemy>
<Enemy>
<ID>EN06</ID>
<Name>Zombie Dragon</Name>
<HP>270</HP>
<MP>60</MP>
<STR>90</STR>
<END>25</END>
<MAG>105</MAG>
<AGI>30</AGI>
<ACC>20</ACC>
<Level>6</Level>
<EXP>35</EXP>
<Gold>75</Gold>
<Element>Dark</Element>
</Enemy>
<Enemy>
<ID>EN07</ID>
<Name>Angel</Name>
<HP>220</HP>
<MP>70</MP>
<STR>80</STR>
<END>35</END>
<MAG>100</MAG>
<AGI>40</AGI>
<ACC>50</ACC>
<Level>7</Level>
<EXP>40</EXP>
<Gold>100</Gold>
<Element>Light</Element>
</Enemy>
<Enemy>
<ID>EN08</ID>
<Name>Dullahan</Name>
<HP>320</HP>
<MP>80</MP>
<STR>200</STR>
<END>50</END>
<MAG>120</MAG>
<AGI>60</AGI>
<ACC>80</ACC>
<Level>8</Level>
<EXP>92</EXP>
<Gold>150</Gold>
<Element>Dark</Element>
</Enemy>
<Enemy>
<ID>EN09</ID>
<Name>Cool Jack</Name>
<HP>300</HP>
<MP>90</MP>
<STR>120</STR>
<END>40</END>
<MAG>100</MAG>
<AGI>65</AGI>
<ACC>40</ACC>
<Level>8</Level>
<EXP>83</EXP>
<Gold>140</Gold>
<Element>Fire</Element>
</Enemy>
<Enemy>
<ID>EN10</ID>
<Name>Scale of Ice</Name>
<HP>400</HP>
<MP>100</MP>
<STR>100</STR>
<END>65</END>
<MAG>30</MAG>
<AGI>35</AGI>
<ACC>30</ACC>
<Level>8</Level>
<EXP>78</EXP>
<Gold>130</Gold>
<Element>Water</Element>
</Enemy>
<Enemy>
<ID>EN11</ID>
<Name>Mad Jotun</Name>
<HP>500</HP>
<MP>110</MP>
<STR>200</STR>
<END>80</END>
<MAG>250</MAG>
<AGI>30</AGI>
<ACC>20</ACC>
<Level>9</Level>
<EXP>156</EXP>
<Gold>200</Gold>
<Element>Fire</Element>
</Enemy>
<Enemy>
<ID>EN12</ID>
<Name>Igna</Name>
<HP>8000</HP>
<MP>1000</MP>
<STR>350</STR>
<END>120</END>
<MAG>280</MAG>
<AGI>60</AGI>
<ACC>70</ACC>
<Level>10</Level>
<EXP>1300</EXP>
<Gold>2000</Gold>
<Element>Neutral</Element>
</Enemy>
<Enemy>
<ID>EN13</ID>
<Name>Xelvaria</Name>
<HP>6000</HP>
<MP>1000</MP>
<STR>260</STR>
<END>80</END>
<MAG>370</MAG>
<AGI>90</AGI>
<ACC>80</ACC>
<Level>10</Level>
<EXP>1100</EXP>
<Gold>1700</Gold>
<Element>Neutral</Element>
</Enemy>
<Enemy>
<ID>EN14</ID>
<Name>Fei Long</Name>
<HP>7000</HP>
<MP>1000</MP>
<STR>380</STR>
<END>100</END>
<MAG>380</MAG>
<AGI>70</AGI>
<ACC>100</ACC>
<Level>10</Level>
<EXP>1100</EXP>
<Gold>1700</Gold>
<Element>Neutral</Element>
</Enemy>
<Enemy>
<ID>EN15</ID>
<Name>Odin</Name>
<HP>30000</HP>
<MP>5000</MP>
<STR>400</STR>
<END>50</END>
<MAG>350</MAG>
<AGI>50</AGI>
<ACC>150</ACC>
<Level>10</Level>
<EXP>5000</EXP>
<Gold>5000</Gold>
<Element>Neutral</Element>
</Enemy>
</dataroot>
