=== segmeton/WorldEndTale-Original-/Assets/DB/EXP.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="EXP" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="EXP">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="GXzYHHAt1EGSXhsPp+yGPg==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAAZfNgccC3UQZJeGw+n7IY+AAAAACxCYikzfuRAAAAAAAAAAABFAFgA
UAAAAAAAAACPvweH2kFMR5AtbZGmpS2wBwAAABl82BxwLdRBkl4bD6fshj5JAEQA
AAAAAAAAKjmM5S43Gk+pY9BvMdAQHAcAAAAZfNgccC3UQZJeGw+n7IY+TABlAHYA
ZQBsAAAAAAAAAMBuPdQ9dxNBhxFBEVnq9FcHAAAAGXzYHHAt1EGSXhsPp+yGPk4A
ZQB4AHQAIABFAFgAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUAAAAAAAAA
AAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="0"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Level" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="KjmM5S43Gk+pY9BvMdAQHA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Next_x0020_EXP" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="wG491D13E0GHEUERWer0Vw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== segmeton/WorldEndTale-Original-/Assets/DB/EXP.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="EXP.xsd" generated="2014-11-30T16:42:37">
<EXP>
<ID>LV01</ID>
<Level>1</Level>
<Next_x0020_EXP>100</Next_x0020_EXP>
</EXP>
<EXP>
<ID>LV02</ID>
<Level>2</Level>
<Next_x0020_EXP>150</Next_x0020_EXP>
</EXP>
<EXP>
<ID>LV03</ID>
<Level>3</Level>
<Next_x0020_EXP>225</Next_x0020_EXP>
</EXP>
<EXP>
<ID>LV04</ID>
<Level>4</Level>
<Next_x0020_EXP>360</Next_x0020_EXP>
</EXP>
<EXP>
<ID>LV05</ID>
<Level>5</Level>
<Next_x0020_EXP>576</Next_x0020_EXP>
</EXP>
<EXP>
<ID>LV06</ID>
<Level>6</Level>
<Next_x0020_EXP>921</Next_x0020_EXP>
</EXP>
<EXP>
<ID>LV07</ID>
<Level>7</Level>
<Next_x0020_EXP>1565</Next_x0020_EXP>
</EXP>
<EXP>
<ID>LV08</ID>
<Level>8</Level>
<Next_x0020_EXP>2661</Next_x0020_EXP>
</EXP>
<EXP>
<ID>LV09</ID>
<Level>9</Level>
<Next_x0020_EXP>4523</Next_x0020_EXP>
</EXP>
<EXP>
<ID>LV10</ID>
<Level>10</Level>
<Next_x0020_EXP>0</Next_x0020_EXP>
</EXP>
</dataroot>
