=== segmeton/WorldEndTale-Original-/Assets/DB/Weapon.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Weapon" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Weapon">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="GUID" type="9" value="4ccRorYJzEiI2VvfxsF5/w==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADhxxGitgnMSIjZW9/GwXn/AAAAAP5gB2BOfuRAAAAAAAAAAABXAGUA
YQBwAG8AbgAAAAAAAAAlsR+mELSfTJC2SAd46HD2BwAAAOHHEaK2CcxIiNlb38bB
ef9JAEQAAAAAAAAArdkKOOS98kGY/TRj6SitwwcAAADhxxGitgnMSIjZW9/GwXn/
TgBhAG0AZQAAAAAAAADkb8lcYjgNQrWkS9AD/1/GBwAAAOHHEaK2CcxIiNlb38bB
ef9CAHUAeQAgAFAAcgBpAGMAZQAAAAAAAABcZbZBcRcjSZglwuYCUhHnBwAAAOHH
EaK2CcxIiNlb38bBef9TAGUAbABsACAAUAByAGkAYwBlAAAAAAAAAKZmtWYfB0VD
p8yaLpU/JwAHAAAA4ccRorYJzEiI2VvfxsF5/1MAVABSAAAAAAAAACIQukAqm/dF
rer0ZemxZy0HAAAA4ccRorYJzEiI2VvfxsF5/00AQQBHAAAAAAAAAJi7bD6RG/JG
sZvVDxg5b8gHAAAA4ccRorYJzEiI2VvfxsF5/0UATgBEAAAAAAAAABwpL9G9h59B
qnhO/jZVZeMHAAAA4ccRorYJzEiI2VvfxsF5/0EARwBJAAAAAAAAAJSrl3/fCtNK
lG4K8HCWF84HAAAA4ccRorYJzEiI2VvfxsF5/0QAZQBzAGMAcgBpAHAAdABpAG8A
bgAAAAAAAACuXwxLoPW1Ra7Igy906HrCBwAAAOHHEaK2CcxIiNlb38bBef9PAGIA
dABhAGkAbgBlAGQAIABiAHkAAAAAAAAA6JwSIaetoEKAgaHSnJCs9gcAAADhxxGi
tgnMSIjZW9/GwXn/QQBDAEMAAAAAAAAAVY6LZoot80mUxaa8UbHUxgcAAADhxxGi
tgnMSIjZW9/GwXn/VQBzAGUAZAAgAGIAeQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ID" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="672"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="0"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="rdkKOOS98kGY/TRj6Sitww==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1584"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="0"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Buy_x0020_Price" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="5G/JXGI4DUK1pEvQA/9fxg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1188"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Sell_x0020_Price" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="XGW2QXEXI0mYJcLmAlIR5w==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1164"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="STR" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="pma1Zh8HRUOnzJoulT8nAA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="708"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="MAG" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="IhC6QCqb90Wt6vRl6bFnLQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="900"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="END" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="mLtsPpEb8kaxm9UPGDlvyA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="900"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="AGI" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="HCkv0b2Hn0GqeE7+NlVl4w==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="900"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ACC" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="6JwSIaetoEKAgaHSnJCs9g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Description" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="lKuXf98K00qUbgrwcJYXzg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="5064"/>
<od:fieldProperty name="ColumnOrder" type="3" value="10"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="0"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== segmeton/WorldEndTale-Original-/Assets/DB/Weapon.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Weapon.xsd" generated="2014-11-30T21:53:30">
<Weapon>
<ID>WP01</ID>
<Name>Iron Sword</Name>
<Buy_x0020_Price>0</Buy_x0020_Price>
<Sell_x0020_Price>150</Sell_x0020_Price>
<STR>5</STR>
<MAG>0</MAG>
<END>0</END>
<AGI>0</AGI>
<ACC>0</ACC>
<Description>A basic sword for every aspiring swordman.</Description>
</Weapon>
<Weapon>
<ID>WP02</ID>
<Name>Gem Sword</Name>
<Buy_x0020_Price>1000</Buy_x0020_Price>
<Sell_x0020_Price>500</Sell_x0020_Price>
<STR>15</STR>
<MAG>0</MAG>
<END>0</END>
<AGI>5</AGI>
<ACC>0</ACC>
<Description>An upgraded sword enchanced by several gemstone.</Description>
</Weapon>
<Weapon>
<ID>WP03</ID>
<Name>Damascus Blade</Name>
<Buy_x0020_Price>3000</Buy_x0020_Price>
<Sell_x0020_Price>1500</Sell_x0020_Price>
<STR>35</STR>
<MAG>0</MAG>s
<END>0</END>
<AGI>10</AGI>
<ACC>0</ACC>
<Description>A sword made from the best ore.</Description>
</Weapon>
<Weapon>
<ID>WP04</ID>
<Name>Sword of Oath</Name>
<Buy_x0020_Price>0</Buy_x0020_Price>
<Sell_x0020_Price>1</Sell_x0020_Price>
<STR>100</STR>
<MAG>50</MAG>
<END>50</END>
<AGI>20</AGI>
<ACC>15</ACC>
<Description>Proof of Relationship between a hero and his comrades.</Description>
</Weapon>
<Weapon>
<ID>WP05</ID>
<Name>Staff</Name>
<Buy_x0020_Price>0</Buy_x0020_Price>
<Sell_x0020_Price>150</Sell_x0020_Price>
<STR>0</STR>
<MAG>7</MAG>
<END>0</END>
<AGI>0</AGI>
<ACC>0</ACC>
<Description>Crudely made staff. Used by novice adventurers.</Description>
</Weapon>
<Weapon>
<ID>WP06</ID>
<Name>Holy Staff</Name>
<Buy_x0020_Price>1000</Buy_x0020_Price>
<Sell_x0020_Price>500</Sell_x0020_Price>
<STR>2</STR>
<MAG>20</MAG>
<END>0</END>
<AGI>5</AGI>
<ACC>0</ACC>
<Description>A staff blessed by the Goddess of Healing.</Description>
</Weapon>
<Weapon>
<ID>WP07</ID>
<Name>Diamond Staff</Name>
<Buy_x0020_Price>3000</Buy_x0020_Price>
<Sell_x0020_Price>1500</Sell_x0020_Price>
<STR>0</STR>
<MAG>45</MAG>
<END>5</END>
<AGI>10</AGI>
<ACC>0</ACC>
<Description>A very precious staff used by sages in the past.</Description>
</Weapon>
<Weapon>
<ID>WP08</ID>
<Name>Rod of Yggdrasil</Name>
<Buy_x0020_Price>0</Buy_x0020_Price>
<Sell_x0020_Price>1</Sell_x0020_Price>
<STR>40</STR>
<MAG>100</MAG>
<END>20</END>
<AGI>30</AGI>
<ACC>10</ACC>
<Description>A staff made from a branch of the Legendary Life Tree.</Description>
</Weapon>
<Weapon>
<ID>WP09</ID>
<Name>Spear</Name>
<Buy_x0020_Price>0</Buy_x0020_Price>
<Sell_x0020_Price>150</Sell_x0020_Price>
<STR>10</STR>
<MAG>0</MAG>
<END>5</END>
<AGI>0</AGI>
<ACC>0</ACC>
<Description>A basic weapon for every knight.</Description>
</Weapon>
<Weapon>
<ID>WP10</ID>
<Name>Lance</Name>
<Buy_x0020_Price>500</Buy_x0020_Price>
<Sell_x0020_Price>175</Sell_x0020_Price>
<STR>20</STR>
<MAG>0</MAG>
<END>10</END>
<AGI>0</AGI>
<ACC>0</ACC>
<Description>A spear with reinforced steel as its head.</Description>
</Weapon>
<Weapon>
<ID>WP11</ID>
<Name>Trident</Name>
<Buy_x0020_Price>3000</Buy_x0020_Price>
<Sell_x0020_Price>1500</Sell_x0020_Price>
<STR>45</STR>
<MAG>0</MAG>
<END>20</END>
<AGI>0</AGI>
<ACC>0</ACC>
<Description>A spear with 3 point for maximum damage</Description>
</Weapon>
<Weapon>
<ID>WP12</ID>
<Name>Legendary Spear</Name>
<Buy_x0020_Price>0</Buy_x0020_Price>
<Sell_x0020_Price>1</Sell_x0020_Price>
<STR>120</STR>
<MAG>0</MAG>
<END>80</END>
<AGI>0</AGI>
<ACC>10</ACC>
<Description>A spear used by a legendary hero in the past</Description>
</Weapon>
</dataroot>
